volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:
  open-webui:
  flowise:

networks:
  demo:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - WEBHOOK_URL=${N8N_URL}
  links:
    - postgres

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['demo']
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['demo']
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 3; OLLAMA_HOST=host.docker.internal:11434 ollama pull llama3.1; OLLAMA_HOST=host.docker.internal:11434 ollama pull nomic-embed-text"

services:
  flowise:
    image: flowiseai/flowise
    networks: ['demo']
    restart: unless-stopped
    container_name: flowise
    environment:
        - PORT=3001
    ports:
        - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"        
    volumes:
        - ~/.flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks: ['demo']
    restart: unless-stopped
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"  # Kết nối trực tiếp qua tên container
    volumes:
      - open-webui:/app/backend/data

  postgres:
    image: postgres:16-alpine
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - ./n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu
  #ngrok:
  #    image: ngrok/ngrok:latest
  #    networks: ['demo']
  #    restart: unless-stopped
  #    environment:
  #      NGROK_AUTHTOKEN: 2tUVcUHSPY73RhxqzdIWhLW8jdu_4moULpa6iAzFTH7MY9ERw
  #    command: ["http", "n8n:5678"] 
  #    ports:
  #      - 4040:4040
  #    depends_on:
  #      - n8n  
  # Uncomment the following block to enable Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    networks: ['demo']
    container_name: chatbot-tunnel
    hostname: chatbot.thuhoai-academy.com
    restart: unless-stopped
    command: tunnel --no-autoupdate run --url http://open-webui:8080
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMGMzY2U1NjRiNjc0ZDdkM2I5ZDM4YTIzNjg3MDU3ZDMiLCJ0IjoiNWMzMGU3OTItY2U3NS00ZDAyLWJmMjYtYzdmOTYyNWUyYjgzIiwicyI6Ik56UmpaVEJqWm1ZdE1ETTNNaTAwTTJZMkxUbGtaR1l0TURjd05UYzFPV1ZqTURJMyJ9
    depends_on:
      - n8n
  cloudflare-tunnel2:
    image: cloudflare/cloudflared:latest
    networks: ['demo']
    container_name: n8n-tunnel
    hostname: n8n.thuhoai-academy.com
    restart: unless-stopped
    command: tunnel --no-autoupdate run --url http://n8n:5678
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMGMzY2U1NjRiNjc0ZDdkM2I5ZDM4YTIzNjg3MDU3ZDMiLCJ0IjoiNDYyOTA5YjAtYzkyOS00MDcwLWJjZjctNDI5ZjJhYmQzNGVmIiwicyI6IllqVmxNakE0TmpNdE4yTmxOeTAwT0RKa0xUbGxOVEV0TlRrd1ltVXlORFF6T1RSaiJ9
    depends_on:
      - n8n
